In [4]:
import pandas as pd
import numpy as np
from sklearn import preprocessing, svm
from sklearn.model_selection import train_test_split

# READING THE DOWNLOADED DATA SET SAVED IN THE SYSTEM
data_frame = pd.read_csv('~/Desktop/bc.csv')

# DELETING THE UNWANTED COLUMNS
first_col = data_frame.columns[0]
second_col = data_frame.columns[1]
data_frame = data_frame.drop([first_col], axis=1)
data_frame = data_frame.drop([second_col], axis=1)

X = np.array(data_frame.drop(['Class'], 1))
y = np.array(data_frame['Class'])

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3, random_state=0)

clf = svm.SVC(kernel='linear', random_state=0)

clf.fit(X_train, y_train)

sv = clf.support_vectors_
print("Support vectors ")
print(sv)

indices = clf.support_
print("Indices of SV ")
print(indices)

numb = clf.n_support_
print("number of SV for each class")
print(numb)

Support vectors 
[[ 8.  4.  4.  5.  4.  7.  7.  8.  2.]
 [ 4.  4.  4.  4.  6.  5.  7.  3.  1.]
 [ 5.  1.  2. 10.  4.  5.  2.  1.  1.]
 [ 6.  8.  8.  1.  3.  4.  3.  7.  1.]
 [ 4.  4.  2.  1.  2.  5.  2.  1.  2.]
 [ 3.  3.  2.  6.  3.  3.  3.  5.  1.]
 [ 6.  9.  7.  5.  5.  8.  4.  2.  1.]
 [ 8.  3.  3.  1.  2.  2.  3.  2.  1.]
 [ 6.  3.  3.  3.  3.  2.  6.  1.  1.]
 [ 3.  1.  1.  1.  2.  5.  5.  1.  1.]
 [ 4.  4.  4.  2.  2.  3.  2.  1.  1.]
 [ 3.  3.  2.  1.  3.  1.  3.  6.  1.]
 [ 8.  4.  6.  3.  3.  1.  4.  3.  1.]
 [ 8.  2.  1.  1.  5.  1.  1.  1.  1.]
 [ 5.  4.  5.  1.  8.  1.  3.  6.  1.]
 [ 5.  1.  4.  1.  2.  1.  3.  2.  1.]
 [ 6.  3.  3.  5.  3. 10.  3.  5.  3.]
 [ 5.  3.  3.  3.  6. 10.  3.  1.  1.]
 [ 4. 10.  8.  5.  4.  1. 10.  1.  1.]
 [ 3.  3.  5.  2.  3. 10.  7.  1.  1.]
 [ 2.  5.  3.  3.  6.  7.  7.  5.  1.]
 [ 3.  6.  4. 10.  3.  3.  3.  4.  1.]
 [ 6.  3.  2.  1.  3.  4.  4.  1.  1.]
 [10.  4.  2.  1.  3.  2.  4.  3. 10.]
 [10.  4.  3.  1.  3.  3.  6.  5.  2.]
 [ 6.  3